name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build LiteX BIOS for QuickFeather
        run: make -f Makefile.quickfeather
      - name: Build LiteX BIOS for Tang Nano 4K
        run: poetry run python lib/litex-boards/litex_boards/targets/sipeed_tang_nano_4k.py --cpu-type=gowin_emcu
      - name: Build LiteX BIOS for Zedboard
        run: make -f Makefile.zedboard build/digilent_zedboard/software/bios/bios.bin
      - name: Build LiteX BIOS for KV260
        run: make -f Makefile.kv260
      - name: Build LiteX BIOS for ZCU216
        run: make -f Makefile.zcu216
